### ISSUE TITLE
可以直接基于成熟的.net core框架开发不？

### ISSUE THREAD

**Issue by xewn** [cnblogs/fluss#12]
有太多成熟的框架可以直接使用，参与的人也可以学习框架的使用
完全从头开发一套，有点浪费精力嗯

**Comment by zhuzhao** [comment]
不可以，闭嘴，马上封你号

**Comment by cnblogs-team** [comment]
您好，就是基于 ASP.NET Core in .NET 5

**Comment by xewn** [comment]
@cnblogs-dudu   哪祝你们早日开发出来

**Comment by xewn** [comment]
abp vnext啊 orleans啊  dapr啊  orchard。这么多框架

**Comment by ojdev** [comment]
@xewn 那些成熟框架直接就能写业务了啊……
没必要二次开发进行改造了吧。
而且，用它们做博客实在是太多没用的东西在里面了。

**Comment by MissGoing** [comment]
> abp vnext啊 orleans啊 dapr啊 orchard。这么多框架

没必要啊，那么多东西压根就用不到

**Comment by xewn** [comment]
嗯，abp和orchard这些是大杂烩。orleans和dapr是很干净的

**Comment by ikesnowy** [comment]
https://github.com/cnblogs/fluss/discussions

讨论类问题建议使用 discussions，希望有对这些框架熟悉的人能够发表一下看法。
