### ISSUE TITLE
Blog picture URL cant visit?

### ISSUE THREAD

**Issue by www516717402** [cnblogs/fluss#37]
Picture in CNBlog blog, when i copy markdown url to local compute (like CSDN/github/local) that cant visit picture url.
Such as : [CNBlog](https://www.cnblogs.com/wjy-lulu/p/14545576.html) -->> [CSDN](https://blog.csdn.net/u011046017/article/details/115121609)

**Comment by ikesnowy** [comment]
Guess you should write to contact@cnblogs.com with details about the problem you've met.
